name: Create Jira issue
on:
  issues:
    types:
      - opened

jobs:
  create-issue:
    name: Create Jira issue
    runs-on: ubuntu-latest
    steps:
      - name: Login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}

      - name: Checkout main code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Issue Parser
        uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/issue-form.yml

      - name: Log Issue Parser
        run: |
          echo "parentKey: ${{ steps.issue-parser.outputs.issueparser_parentKey }}"
          echo "parentIssueType: ${{ steps.issue-parser.outputs.parentIssueType }}"
          echo "ticket number: ${{ steps.issue-parser.outputs.__ticket_number }}"
          echo "json: ${{ steps.issue-parser.outputs.jsonString }}"

      - name: Get Parent Issue Type from Jira
        id: get-parent-type
        if: ${{ steps.issue-parser.outputs.issueparser_parentKey != '' }}
        shell: bash
        run: |
          set -x
          
          PARENT_KEY="${{ steps.issue-parser.outputs.issueparser_parentKey }}"
          echo "🔍 Fetching issue type for: $PARENT_KEY"
          
          HTTP_RESPONSE=$(curl -s -w "\nHTTP_STATUS:%{http_code}" -X GET \
            -H "Authorization: Basic $(echo -n ${{ secrets.JIRA_USER_EMAIL }}:${{ secrets.JIRA_API_TOKEN }} | base64)" \
            -H "Content-Type: application/json" \
            "${{ secrets.JIRA_BASE_URL }}/rest/api/3/issue/${PARENT_KEY}")
          
          HTTP_BODY=$(echo "$HTTP_RESPONSE" | sed -n '1,/HTTP_STATUS:/p' | sed '$d')
          HTTP_STATUS=$(echo "$HTTP_RESPONSE" | grep "HTTP_STATUS:" | cut -d':' -f2)
          
          echo "📊 HTTP Status: $HTTP_STATUS"
          echo "📦 Response Body:"
          echo "$HTTP_BODY"
          
          if [ "$HTTP_STATUS" != "200" ]; then
            echo "❌ API call failed with status $HTTP_STATUS"
            exit 1
          fi
          
          # Python으로 JSON 파싱
          ISSUE_TYPE=$(echo "$HTTP_BODY" | python3 << 'PYTHON_SCRIPT'
          import sys
          import json

          try:
              data = json.load(sys.stdin)
              
              if 'errorMessages' in data or 'errors' in data:
                  print(f"❌ Jira API Error: {data}", file=sys.stderr)
                  sys.exit(1)
              
              if 'fields' not in data or 'issuetype' not in data['fields']:
                  print(f"❌ Required fields not found", file=sys.stderr)
                  sys.exit(1)
              
              issue_type = data['fields']['issuetype']['name']
              print(issue_type)
              
          except Exception as e:
              print(f"❌ Error: {e}", file=sys.stderr)
              sys.exit(1)
          PYTHON_SCRIPT
          )
          
          if [ $? -ne 0 ]; then
            echo "❌ Failed to parse issue type"
            exit 1
          fi
          
          echo "parent_issue_type=${ISSUE_TYPE}" >> $GITHUB_OUTPUT
          echo "✅ Parent issue type is: ${ISSUE_TYPE}"

      - name: Convert markdown to Jira Syntax
        uses: peter-evans/jira2md@v1
        id: md2jira
        with:
          input-text: |
            ### Github Issue Link
            - ${{ github.event.issue.html_url }}

            ${{ github.event.issue.body }}
          mode: md2jira

      - name: Create Task under Epic
        id: create-epic
        if: ${{ steps.get-parent-type.outputs.parent_issue_type == 'Epic' }}
        uses: atlassian/gajira-create@v3
        with:
          project: SGK
          issuetype: Task
          summary: '${{ github.event.issue.title }}'
          description: '${{ steps.md2jira.outputs.output-text }}'
          fields: |
            {
              "customfield_10014": "${{ steps.issue-parser.outputs.issueparser_parentKey }}"
            }

      - name: Create Sub-task under Task
        id: create-subtask
        if: ${{ steps.get-parent-type.outputs.parent_issue_type == 'Task' }}
        uses: atlassian/gajira-create@v3
        with:
          project: SGK
          issuetype: Sub-task
          summary: '${{ github.event.issue.title }}'
          description: '${{ steps.md2jira.outputs.output-text }}'
          fields: |
            {
              "parent": {
                "key": "${{ steps.issue-parser.outputs.issueparser_parentKey }}"
              }
            }

      - name: Log created issue
        run: |
          echo "Epic issue: ${{ steps.create-epic.outputs.issue }}"
          echo "Subtask issue: ${{ steps.create-subtask.outputs.issue }}"

      - name: Checkout develop code
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Create branch with Ticket number
        run: |
          ISSUE_NUMBER="${{ steps.create-epic.outputs.issue }}"
          if [ -z "$ISSUE_NUMBER" ]; then
            ISSUE_NUMBER="${{ steps.create-subtask.outputs.issue }}"
          fi

          if [ -z "$ISSUE_NUMBER" ]; then
            echo "No Jira issue created (parent type was neither Epic nor Task). Exiting."
            exit 0
          fi

          ISSUE_TITLE="${{ steps.issue-parser.outputs.issueparser_branch }}"
          BRANCH_NAME="${ISSUE_NUMBER}-$(echo ${ISSUE_TITLE} | sed 's/ /-/g')"
          git checkout -b "${BRANCH_NAME}"
          git push origin "${BRANCH_NAME}"

      - name: Update issue title
        if: ${{ steps.create-epic.outputs.issue || steps.create-subtask.outputs.issue }}
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'update-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          title: '[${{ steps.create-epic.outputs.issue || steps.create-subtask.outputs.issue }}] ${{ github.event.issue.title }}'

      - name: Add comment with Jira issue link
        if: ${{ steps.create-epic.outputs.issue || steps.create-subtask.outputs.issue }}
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Jira Issue Created: [${{ steps.create-epic.outputs.issue || steps.create-subtask.outputs.issue }}](${{ secrets.JIRA_BASE_URL }}/browse/${{ steps.create-epic.outputs.issue || steps.create-subtask.outputs.issue }})
